name = "App-optex-xform"
badges = ["travis-ci.com"]
authority="cpan:UTASHIRO"

module_maker="ModuleBuildTiny"
static_install = "auto"

[unsupported]
os = [
    "MSWin32",
]

[FileGatherer]
exclude_match=['^images/.*']

