name = "App-optex-xform"
badges = ["travis-ci.com"]
authority="cpan:UTASHIRO"

module_maker="ModuleBuildTiny"
static_install = "auto"

[release]
do_not_upload_to_cpan = true

[FileGatherer]
exclude_match=['^images/.*']

